version: '3'
services:
  hub:
    image: selenium/hub
    ports:
      - '4444:4444'
    # environment:
    #   -

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - hub
    links:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  tester:
    image: test/runner
    build:
      context: ./
      dockerfile: tester.Dockerfile
    volumes:
      - "./testcases:/testcases"
    command: tail -f /dev/null
    depends_on:
      - chrome
